# arxivの学問領域の指定
subject: 'astro-ph'

# 検索キーワード
keywords:
        protoplanetary disk: 3
        protoplanetary disks: 3
        protoplanetary disc: 3
        protoplanetary discs: 3
        protostar: 3
        protostars: 3
        protostellar disk: 3
        protostellar disc: 3
        protostellar disks: 3
        protostellar discs: 3
        protostellar envelopes: 3
        protostellar: 2
        IMF: 2
        CMF: 2
        CMFs: 2
        core mass function: 2
        core mass functions: 2
        initial mass function: 2
        initial mass functions: 2
        VeLLOs: 2
        debris disk: 1
        debris disks: 1
        debris disc: 1
        debris discs: 1
        star formation: 1
        planet formation: 1
        disk formation: 1
        circumstellar disk: 1
        circumstellar disks: 1
        circumbinary disk: 1
        circumbinary disks: 1
        protoplanet: 1
        exoplanet: 1

# 通知の閾値
score_threshold: 0
